export const fields = [
    { name: 'NumeroDocumento', label: 'Número Documento' },
    { name: 'Bodega', label: 'Bodega' },
    { name: 'Cant_Original', label: 'Cantidad Original' },
    { name: 'Cant_Remisionada', label: 'Cantidad Remisionada' },
    { name: 'Centro_Costos', label: 'Centro Costos' },
    { name: 'Cod_Ubicacion', label: 'Cod Ubicación' },
    { name: 'Detalle', label: 'Detalle' },
    { name: 'Fecha_Dcto', label: 'Fecha Documento' },
    { name: 'Cliente', label: 'Cliente' },
    { name: 'Tipo_Cartera', label: 'Tipo Cartera' },
    { name: 'Tipo_Mvto', label: 'Tipo Movimiento' },
    { name: 'Vendedor', label: 'Vendedor' },
    { name: 'Nota', label: 'Nota' },
    { name: 'Enviadoa', label: 'Enviado a' },
    { name: 'CodCiudadEnvio', label: 'Cod Ciudad Envío' },
    { name: 'OrdenCompra', label: 'Orden Compra' },
    { name: 'CREO_FACT', label: 'Creó Factura' },
    { name: 'Impuestos', label: 'Impuestos' },
    { name: 'nit', label: 'NIT' },
    { name: 'Producto', label: 'Producto' },
    { name: 'CodRete', label: 'Cod Rete' },
    { name: 'CodRetica', label: 'Cod Retica' },
    { name: 'Total_Bruto', label: 'Total Bruto' },
    { name: 'Total_Prod', label: 'Total Producto' },
    { name: 'Total_IVA', label: 'Total IVA' },
    { name: 'Total_Neto', label: 'Total Neto' },
    { name: 'Origen', label: 'Origen' },
    { name: 'TipoDcto', label: 'Tipo Documento' },
    { name: 'NroDcto', label: 'Número Documento' },
  ];
  
  export const operators = [
    { name: '=', label: '=' },
    { name: '!=', label: '!=' },
    { name: '<', label: '<' },
    { name: '<=', label: '<=' },
    { name: '>', label: '>' },
    { name: '>=', label: '>=' },
    { name: 'contains', label: 'contains' },
    { name: 'beginsWith', label: 'begins with' },
    { name: 'endsWith', label: 'ends with' },
  ];