const initialData = [
    { firstName: 'Sebastian', lastName: 'Londoño', age: 28 },
    { firstName: 'Andres', lastName: 'Londoño', age: 34 },
    { firstName: 'Naty', lastName: 'Rodriguez', age: 45 },
    { firstName: 'Sofia', lastName: 'Montes', age: 22 },
    { firstName: 'Jordan', lastName: 'Rendon', age: 38 },
    { firstName: 'Sandra', lastName: 'Urrego', age: 29 },
    { firstName: 'Manuela', lastName: 'Londoño', age: 41 },
    { firstName: 'Sofia', lastName: 'Naranjo', age: 27 },
    { firstName: 'Laura', lastName: 'Moore', age: 36 },
    { firstName: 'James', lastName: 'Martin', age: 50 },
    { firstName: 'Sophia', lastName: 'Jackson', age: 24 },
    { firstName: 'Robert', lastName: 'Lee', age: 42 },
    { firstName: 'Olivia', lastName: 'Harris', age: 30 },
    { firstName: 'William', lastName: 'Clark', age: 33 },
    { firstName: 'Isabella', lastName: 'Lewis', age: 26 },
    { firstName: 'Alexander', lastName: 'Walker', age: 39 },
    { firstName: 'Mia', lastName: 'Hall', age: 21 },
    { firstName: 'Ethan', lastName: 'Allen', age: 35 },
    { firstName: 'Ava', lastName: 'Young', age: 28 },
    { firstName: 'Benjamin', lastName: 'King', age: 44 },
    { firstName: 'Charlotte', lastName: 'Wright', age: 32 },
    { firstName: 'Lucas', lastName: 'Scott', age: 37 },
    { firstName: 'Amelia', lastName: 'Green', age: 25 },
    { firstName: 'Henry', lastName: 'Adams', age: 40 },
    { firstName: 'Evelyn', lastName: 'Baker', age: 29 },
    { firstName: 'Sebastian', lastName: 'Gonzalez', age: 31 },
    { firstName: 'Harper', lastName: 'Nelson', age: 23 },
    { firstName: 'Jack', lastName: 'Carter', age: 34 },
    { firstName: 'Ella', lastName: 'Mitchell', age: 27 },
];

export default initialData;